### ISSUE TITLE
Error line 1507 in OmniStackCmds.psm1

### ISSUE THREAD

**Issue by seananayaveeam** [tbeha/SimpliVity#2]
"OmniStackCmds.psm1" file, line 1507 (GetOmniStackHosts) - "function" was spelled wrong.

**Comment by tbeha** [comment]
I am sorry, but I didn't find the wrong spelled function. 
On the other hand I replaced OmniStackCmds.psm1 by SimpliVity-PS-Cmdlets.psm1 and updated, tested the scripts with this extended cmdlet.
