### ISSUE TITLE
Sort descending fails in OmniStackCmds.psm1

### ISSUE THREAD

**Issue by seananayaveeam** [tbeha/SimpliVity#3]
In that file, on line 444 sort descending is broken.
If sort descending is removed it works properly
 the text in bold was removed…    $z = $bck.backups.created_at | **sort descending**

**Comment by tbeha** [comment]
Fixed by replacing sort descending with SORT-OBJECT -Descending.
This Fix is now in the active branch (SimpliVity-PS-Cmdlets-v3).
